### ISSUE TITLE
Support the use of db connection urls

### ISSUE THREAD

**Issue by ako977** [gradealabs/flock#2]
When specifying the credentials, etc. for the database, support specifying it as a DATABASE_URL environment var (or something similar).
This allows for easy integration in deployment environments like Heroku that by default provides connection urls for db connections

**Comment by dschnare** [comment]
That's a good point. This will come down to each individual database driver looking for this environment variable. I'm perfectly ok with that. As part of our docs we'd indicate that to be a good database driver citizen you should

1. Read connection configuration information from environment variables
1. Support a single connection string in the environment variable `DATABASE_URL`

**Comment by dschnare** [comment]
Related to #4
